In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option("display.max_columns",None)
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split

In [2]:
data =pd.read_csv("heart.csv")


# Heart_Attack is my target variable.

In [3]:
data.head()

ID  Age  Gender Region  Blood_Pressure  Cholesterol   BMI  Heart_Rate  \
0  1.0   50    Male  Rural           110.0        196.5  15.9        76.0   
1  2.0   40  Female  Urban           138.8        157.5  27.1        82.0   
2  3.0   26    Male  Rural           116.0        210.1  27.2        71.0   
3  4.0   54  Female  Rural           133.5        170.5  26.0        74.0   
4  5.0   19  Female  Urban           108.0        224.5  27.5        67.0   

  Exercise_Level Smoking Alcohol_Consumption Diabetes Family_History  \
0           High   False            Moderate    False          False   
1       Moderate   False                 NaN    False           True   
2       Moderate   False            Moderate     True          False   
3       Moderate    True            Moderate    False           True   
4            Low   False                 NaN    False           True   

   Stress_Level Heart_Attack Angina Heart_Disease_History       Diet  \
0           8.0        False  False                 False  Unhealthy   
1           5.0        False   True                 False  Unhealthy   
2           8.0        False  False                 False  Unhealthy   
3           5.0        False  False                 False    Healthy   
4           1.0        False  False                 False  Unhealthy   

   Sleep_Hours  Occupation Income_Level Physical_Activity Education_Level  \
0          9.4  Unemployed          Low               Low         Primary   
1          5.5    Employed          Low          Moderate          Higher   
2          8.8    Employed       Middle              High         Primary   
3          8.2     Student       Middle          Moderate          Higher   
4          5.9    Employed       Middle               Low          Higher   

  Marital_Status Urban_Rural Medication  Health_Awareness  Daily_Water_Intake  \
0        Married       Rural      False               5.0                 2.3   
1        Married       Urban      False               1.0                 5.0   
2        Married       Urban      False               4.0                 2.4   
3        Married       Urban      False               2.0                 2.7   
4        Widowed       Urban      False               4.0                 3.5   

   Mental_Health Obesity  
0            5.0   False  
1            4.0   False  
2            8.0   False  
3            6.0    True  
4            4.0    True

In [4]:
data.info() #no inconsistent data type 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   ID                     49970 non-null  float64
 1   Age                    50000 non-null  int64  
 2   Gender                 50000 non-null  object 
 3   Region                 49972 non-null  object 
 4   Blood_Pressure         49969 non-null  float64
 5   Cholesterol            50000 non-null  float64
 6   BMI                    50000 non-null  float64
 7   Heart_Rate             49909 non-null  float64
 8   Exercise_Level         49820 non-null  object 
 9   Smoking                49897 non-null  object 
 10  Alcohol_Consumption    24904 non-null  object 
 11  Diabetes               49897 non-null  object 
 12  Family_History         49897 non-null  object 
 13  Stress_Level           49886 non-null  float64
 14  Heart_Attack           49897 non-null  object 
 15  An

# Checking redundant columns i.e. ID

In [5]:
data.drop("ID",axis=1,inplace=True)

In [6]:
data.shape

(50000, 29)

In [7]:
data.head(1)

Age Gender Region  Blood_Pressure  Cholesterol   BMI  Heart_Rate  \
0   50   Male  Rural           110.0        196.5  15.9        76.0   

  Exercise_Level Smoking Alcohol_Consumption Diabetes Family_History  \
0           High   False            Moderate    False          False   

   Stress_Level Heart_Attack Angina Heart_Disease_History       Diet  \
0           8.0        False  False                 False  Unhealthy   

   Sleep_Hours  Occupation Income_Level Physical_Activity Education_Level  \
0          9.4  Unemployed          Low               Low         Primary   

  Marital_Status Urban_Rural Medication  Health_Awareness  Daily_Water_Intake  \
0        Married       Rural      False               5.0                 2.3   

   Mental_Health Obesity  
0            5.0   False

# Checking duplicate rows 

In [8]:
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
49995    False
49996    False
49997    False
49998    False
49999    False
Length: 50000, dtype: bool

In [9]:
data[data.duplicated()]

Empty DataFrame
Columns: [Age, Gender, Region, Blood_Pressure, Cholesterol, BMI, Heart_Rate, Exercise_Level, Smoking, Alcohol_Consumption, Diabetes, Family_History, Stress_Level, Heart_Attack, Angina, Heart_Disease_History, Diet, Sleep_Hours, Occupation, Income_Level, Physical_Activity, Education_Level, Marital_Status, Urban_Rural, Medication, Health_Awareness, Daily_Water_Intake, Mental_Health, Obesity]
Index: []

# Checking null values 

In [10]:
data.shape

(50000, 29)

In [11]:
data.isnull().sum()/data.shape[0]*100

Age                       0.000
Gender                    0.000
Region                    0.056
Blood_Pressure            0.062
Cholesterol               0.000
BMI                       0.000
Heart_Rate                0.182
Exercise_Level            0.360
Smoking                   0.206
Alcohol_Consumption      50.192
Diabetes                  0.206
Family_History            0.206
Stress_Level              0.228
Heart_Attack              0.206
Angina                    0.284
Heart_Disease_History     0.142
Diet                      0.142
Sleep_Hours               0.142
Occupation                0.276
Income_Level              0.142
Physical_Activity         0.140
Education_Level           0.140
Marital_Status            0.190
Urban_Rural               0.188
Medication                0.138
Health_Awareness          0.138
Daily_Water_Intake        0.138
Mental_Health             0.138
Obesity                   0.002
dtype: float64

In [12]:
data.Heart_Attack.unique()

array([False, True, nan], dtype=object)

In [13]:
d = data[data["Heart_Attack"].isnull()==True].index

In [14]:
d

Index([ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
       ...
       267, 289, 290, 291, 292, 293, 294, 295, 296, 297],
      dtype='int64', length=103)

In [15]:
data.drop(d,inplace=True)

# Filling null values 

In [16]:
data.isnull().sum()/data.shape[0]*100

Age                       0.000000
Gender                    0.000000
Region                    0.056116
Blood_Pressure            0.000000
Cholesterol               0.000000
BMI                       0.000000
Heart_Rate                0.000000
Exercise_Level            0.154318
Smoking                   0.000000
Alcohol_Consumption      50.089184
Diabetes                  0.000000
Family_History            0.000000
Stress_Level              0.022045
Heart_Attack              0.000000
Angina                    0.090186
Heart_Disease_History     0.002004
Diet                      0.002004
Sleep_Hours               0.002004
Occupation                0.128264
Income_Level              0.002004
Physical_Activity         0.002004
Education_Level           0.002004
Marital_Status            0.044091
Urban_Rural               0.044091
Medication                0.002004
Health_Awareness          0.002004
Daily_Water_Intake        0.002004
Mental_Health             0.002004
Obesity             

In [17]:
for i in data.select_dtypes(include="object"):
    data[i].fillna(data[i].mode()[0],inplace=True)

In [18]:
data.Alcohol_Consumption.mode()[0]

'Moderate'

In [19]:
for i in data.select_dtypes(exclude="object"):
    data[i].fillna(data[i].mean(),inplace=True)

In [20]:
data.isnull().sum()/data.shape[0]*100

Age                      0.0
Gender                   0.0
Region                   0.0
Blood_Pressure           0.0
Cholesterol              0.0
BMI                      0.0
Heart_Rate               0.0
Exercise_Level           0.0
Smoking                  0.0
Alcohol_Consumption      0.0
Diabetes                 0.0
Family_History           0.0
Stress_Level             0.0
Heart_Attack             0.0
Angina                   0.0
Heart_Disease_History    0.0
Diet                     0.0
Sleep_Hours              0.0
Occupation               0.0
Income_Level             0.0
Physical_Activity        0.0
Education_Level          0.0
Marital_Status           0.0
Urban_Rural              0.0
Medication               0.0
Health_Awareness         0.0
Daily_Water_Intake       0.0
Mental_Health            0.0
Obesity                  0.0
dtype: float64

In [21]:
data.Heart_Attack = data["Heart_Attack"].astype(np.number)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/dtypes/common.py:1645: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  npdtype = np.dtype(dtype)


In [22]:
x=data.drop("Heart_Attack",axis=1)
y=data.Heart_Attack

In [23]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=13)

# Outlier treatment 

In [24]:
for i in xtrain.select_dtypes(include=np.number):
    q1=xtrain[i].quantile(0.25)
    q3=xtrain[i].quantile(0.75)
    iqr=q3-q1
    u=q3+1.5*iqr
    l=q1-1.5*iqr
    xtrain[i]=xtrain[i].clip(lower=l,upper=u)

In [25]:
for i in xtrain.select_dtypes(include="object"):
    print(i)
    print(xtrain[i].unique())

Gender
['Male' 'Female' 'Other']
Region
['Urban' 'Suburban' 'Rural']
Exercise_Level
['High' 'Low' 'Moderate']
Smoking
[False True]
Alcohol_Consumption
['Moderate' 'Heavy']
Diabetes
[False True]
Family_History
[False True]
Diet
['Healthy' 'Unhealthy' 'Mixed']
Occupation
['Student' 'Retired' 'Unemployed' 'Employed']
Income_Level
['Middle' 'Low' 'High']
Physical_Activity
['Moderate' 'High' 'Low']
Education_Level
['Primary' 'Higher' 'Secondary']
Marital_Status
['Married' 'Single' 'Widowed' 'Divorced']
Urban_Rural
['Rural' 'Urban']
Obesity
[False True]


## Converting data into numeric values to make computer understand the data


## Ordinal Data (Ordered data which have co-relatioin)
### Physical_Activity , Education_Level , Diet , Alcohol_Consumption , Exercise_Level


In [26]:
xtrain["Physical_Activity"]=xtrain["Physical_Activity"].apply(lambda x:3 if x=='High' else 2 if x=='Moderate' else 1)


In [27]:
xtrain["Physical_Activity"].unique()

array([2, 3, 1])

# Nominal Data
### Urban_Rural , Obestiy , Smoking , Diabetes , Family_History

In [28]:
xtrain["Obesity"]=xtrain["Obesity"].apply(lambda x:1 if x==True else 0)
xtrain["Obesity"].unique()

array([0, 1])

In [29]:
xtrain["Urban_Rural"]=xtrain["Urban_Rural"].apply(lambda x:1 if x=="Rural" else 0)
xtrain["Urban_Rural"].unique()

array([1, 0])

# One-Hot Encoding

In [30]:
xtrain["Marital_Status"].unique()


array(['Married', 'Single', 'Widowed', 'Divorced'], dtype=object)

In [31]:
marital= pd.get_dummies(xtrain["Marital_Status"])
marital= marital.astype(np.number)

xtrain= pd.concat([xtrain, marital], axis=1)
xtrain.drop("Marital_Status", axis=1, )
xtrain

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/dtypes/common.py:1645: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  npdtype = np.dtype(dtype)


Age  Gender    Region  Blood_Pressure  Cholesterol   BMI  Heart_Rate  \
14674   35    Male     Urban           138.5        210.5  25.2        62.0   
27505   46    Male  Suburban           133.4        158.4  29.1        74.0   
12911   58  Female     Urban           101.8        181.8  29.8        65.0   
9921    47  Female     Urban           116.0        168.3  27.9        84.0   
9711    40  Female     Urban           119.5        236.5  26.4        84.0   
...    ...     ...       ...             ...          ...   ...         ...   
22363   24  Female  Suburban           116.6        262.1  21.4        71.0   
33737   34    Male     Rural           119.6        250.9  27.9        77.0   
32945   32    Male     Rural            97.1        154.0  23.6        73.0   
47383   46    Male     Urban           110.5        163.5  25.0        81.0   
33209   59    Male  Suburban           109.9        166.4  20.7        60.0   

      Exercise_Level Smoking Alcohol_Consumption Diabetes Family_History  \
14674           High   False            Moderate    False          False   
27505            Low    True            Moderate    False          False   
12911            Low   False            Moderate     True          False   
9921             Low   False            Moderate    False          False   
9711        Moderate   False            Moderate    False          False   
...              ...     ...                 ...      ...            ...   
22363            Low    True            Moderate    False          False   
33737       Moderate    True            Moderate     True          False   
32945       Moderate   False            Moderate    False           True   
47383            Low   False            Moderate    False          False   
33209            Low   False            Moderate    False           True   

       Stress_Level  Angina  Heart_Disease_History       Diet  Sleep_Hours  \
14674          10.0   False                  False    Healthy          6.5   
27505           7.0   False                  False  Unhealthy          4.5   
12911           8.0   False                  False  Unhealthy          9.2   
9921            2.0   False                  False  Unhealthy          7.6   
9711            3.0    True                  False  Unhealthy          4.6   
...             ...     ...                    ...        ...          ...   
22363           3.0   False                  False      Mixed          5.9   
33737           6.0   False                  False    Healthy          9.3   
32945           2.0   False                  False      Mixed          4.3   
47383           6.0   False                  False    Healthy          4.4   
33209           1.0   False                  False  Unhealthy          5.6   

       Occupation Income_Level  Physical_Activity Education_Level  \
14674     Student       Middle                  2         Primary   
27505     Student       Middle                  2         Primary   
12911     Retired          Low                  2          Higher   
9921   Unemployed          Low                  3       Secondary   
9711     Employed       Middle                  3       Secondary   
...           ...          ...                ...             ...   
22363    Employed          Low                  2       Secondary   
33737    Employed       Middle                  3          Higher   
32945     Student          Low                  3         Primary   
47383     Student       Middle                  2         Primary   
33209  Unemployed          Low                  2          Higher   

      Marital_Status  Urban_Rural  Medication  Health_Awareness  \
14674        Married            1       False               5.0   
27505         Single            1       False               1.0   
12911         Single            0       False               5.0   
9921         Married            1       False               1.0   
9711         Married            0       Fals

## normalize = True is used to convert the values in percentage

In [32]:
xtrain["Occupation"].value_counts(normalize=True)*100

Occupation
Employed      50.509808
Student       20.089185
Unemployed    19.543052
Retired        9.857955
Name: proportion, dtype: float64